service: email-api  # this defines the project name

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send
          method: post
          cors: true

plugins:
  - serverless-offline
